import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "./ThemeProvider";
import Navbar from "./components/Navbar";
import Main from "./components/Main";

export const metadata: Metadata = {
  title: "Dictionary App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <Main>
          <Navbar />
          {children}
        </Main>
      </ThemeProvider>
    </html>
  );
}
